### ISSUE TITLE
No event for when terminal is closed?

### ISSUE THREAD

**Issue by N-Morris** [Hexworks/zircon#76] opened 2018-03-21 11:47 UTC
I'm using zircon as my main graphics in a game, but when i close the terminal and java exits, The audio thread has not been closed, and is likely still running.I have no direct control over the audio thread, so I can't get the thread to check if it's closed. Could a `terminal.onClosed(event)`, or even just an additional `InputType` to support "terminal closed" be created?

**Comment by adam-arold** [comment] 2018-03-21 12:08
Hi @N-Morris! So you want to be able to be notified when the user exits to perform some cleanup?

**Comment by N-Morris** [comment] 2018-03-22 06:36
That is correct. Is there a way to do this currently? I couldn't see any handlers for it.

**Comment by adam-arold** [comment] 2018-03-22 08:07
I'll figure out a solution for you. There are some circumstances where cleanup cannot be performed. 

For example is the user sends a `SIGKILL` signal (or forces close in Windows) the cleanup will be skipped.

For the normal cases I'll get back to you with a solution. Which Zircon version do you use?

**Comment by N-Morris** [comment] 2018-03-22 10:18
I'm currently using 2017.4.0-RELEASE.

**Comment by adam-arold** [comment] 2018-03-22 21:30
You are right, there is no option for cleanup right now. While I fix this I'd suggest for you to use the latest snapshot (accessible [here](https://jitpack.io/#Hexworks/Zircon/2018.1.6-PREVIEW)) from JitPack.

**Comment by adam-arold** [comment] 2018-03-22 21:46
I've added the `ShutdownHook` interface to the `Terminal` so from now you can use the `onShutdown` method on a `Terminal` to listen for the JVM shutdown event. Please use the latest snapshot (more info [here](https://jitpack.io/#Hexworks/Zircon/2018.1.7-PREVIEW)):

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
        compile 'com.github.Hexworks.Zircon:zircon.core:2018.1.7-PREVIEW'
}
```

**Comment by N-Morris** [comment] 2018-03-24 04:38
Thank you for your help. I have updated my project to use the 2018.1.7-PREVIEW version, but am having problems upgrading the implementation in my project, namely in usage of the `TerminalBuilder` (I believe `VirtualTerminalBuilder` can be used?) and `CP437TilesetResource` with both `toFont()` and `loadFont()`. Is there a documentation page for this version anywhere?

**Comment by adam-arold** [comment] 2018-03-24 09:21
Use the `SwingTerminalBuilder`. `CP437TilesetResource` can only be used *after* instantiating a terminal builder. This is a limitation which will be worked around later and this is caused by supporting multiple platforms (swing, libgdx). In the final release this will be fixed!

**Comment by N-Morris** [comment] 2018-03-24 13:09
Sorry, but I can't seem to find `SwingTerminalBuilder`. I have `Terminal`, `TerminalBuilder`, `TerminalResizeListener`, `TerminalScreen`, `VirtualTerminalBuilder`, and `VirtualTerminal` all available, but no `SwingTerminalBuilder`.

**Comment by LJNIC** [comment] 2018-03-24 13:12
Did you add the Swing version as a dependency?

**Comment by N-Morris** [comment] 2018-03-24 13:46
No I didn't, thank you for that. However, I'm still getting a `java.util.NoSuchElementException: No value present` when trying to load fonts. 
My code is structured as follows: 
`terminal = SwingTerminalBuilder.newBuilder().settings().font(myFont).build();`

**Comment by adam-arold** [comment] 2018-03-24 16:42
Oh, so the problem is that in Java you can't initialize a class with default values across modules. So this means that in `zircon.core` you can't initialize the `FontLoaderRegistry` with swing fonts. 

So this is how you use it for now:

```
        final Terminal terminal = TerminalUtils.fetchTerminalBuilder(args)
                .initialTerminalSize(TERMINAL_SIZE)
                .font(CP437TilesetResource.ROGUE_YUN_16X16.toFont())
                .deviceConfiguration(DeviceConfigurationBuilder.newBuilder()
                        .cursorBlinking(true)
                        .cursorStyle(CursorStyle.USE_CHARACTER_FOREGROUND)
                        .cursorColor(TextColorFactory.fromString("#ff00ff"))
                        .build())
                .build();
```

You need to create a new `TerminalBuilder` (`SwingTerminalBuilder` or `VirtualTerminalBuilder`) and it will initialize the fonts and **after that** you can pick a font like in the example above.

This is a known limitation and I'll work around it somehow. This is a limitation of Java itself. static initialized blocks are not run when the class is loaded but when the class is instantiated. But the `zircon.core` module does not know about the implementations since they are in different modules.

**Comment by adam-arold** [comment] 2018-03-24 23:52
Ok, I fixed this issue. If you try it with the latest `PREVIEW`:

```
dependencies {
    compile 'com.github.hexworks:zircon:2018.1.8-PREVIEW'
}
```

this should work without problems:

```kotlin

final Font font = CP437TilesetResource.ROGUE_YUN_16X16.toFont();

final Terminal terminal = TerminalUtils.fetchTerminalBuilder(args)
                .initialTerminalSize(TERMINAL_SIZE)
                .font(font)
                .deviceConfiguration(DeviceConfigurationBuilder.newBuilder()
                        .cursorBlinking(true)
                        .cursorStyle(CursorStyle.USE_CHARACTER_FOREGROUND)
                        .cursorColor(TextColorFactory.fromString("#ff00ff"))
                        .build())
                .build();
```

**Comment by N-Morris** [comment] 2018-03-25 00:46
Yes, this has worked. Thank you so much for your time.

**Comment by adam-arold** [comment] 2018-03-25 08:41
Cool! Feel free to open an issue if you have any other problems.

**Closed by adam-arold** 2018-03-25 08:41 UTC
Labels: enhancement
